name: OCaml CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.0.x
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build